version: "3.9"
services:
  mongo_db:
    image: mongo:4.4.18
    restart: always
    volumes:
         - mongo_db:/data/db
    
  api:
    build: .
    ports:
      - 3000:3000
    environment:
      - MONGODB_URI=mongodb://mongo_db:27017
      - DB_NAME=todo
      - SECRET=hhshhshhhshhshshs
    depends_on:
      - mongo_db
volumes:
  
  mongo_db: {}
